# Generated by Django 6.0.2 on 2026-02-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='รหัสผ่านตัวจริงสำหรับแจ้งลูกบ้าน', max_length=128, null=True),
        ),
    ]
