# Generated by Django 6.0.2 on 2026-02-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('resident', 'ลูกบ้าน'), ('officer', 'นิติ'), ('technician', 'ช่าง')], max_length=10),
        ),
    ]
