# Generated by Django 5.2.12 on 2026-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='รหัสผ่านตัวจริงจาก n8n', max_length=128, null=True),
        ),
    ]
