# Generated by Django 5.2.12 on 2026-03-17 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_userprofile_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='raw_password',
            field=models.CharField(blank=True, help_text='รหัสผ่านตัวจริงจาก n8n (ใช้สำหรับแจ้งผู้ใช้)', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('resident', 'ลูกบ้าน'), ('officer', 'นิติ'), ('technician', 'ช่าง'), ('admin', 'ผู้ดูแลระบบ')], default='resident', max_length=20),
        ),
    ]
