# Generated by Django 5.2.12 on 2026-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_maintenancerequest_approved_completion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme_accent',
            field=models.CharField(default='blue', help_text='Preferred UI accent color', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_mode',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', help_text='Preferred UI theme', max_length=10),
        ),
    ]
